name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
  #  - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Foo bre
        run: |
            pwd
            ls
            env
      - uses: actions/checkout@v2
      - run: |
            pwd
            ls
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress **/*.md **/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
