on: 
  #- push
  - workflow_dispatch

name: 🚀 www.campbellluggblackwell.com on BlueHost
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.samkirkland.cxxxom
        username: ${{ secrets.BLUEHOST_USERNAME }}
        password: ${{ secrets.BLUEHOST_PASSwORD }}
        dry-run: true
        local-dir: ./website/
        server-dir: ./public_html/dev/
        
