# On any change to the ./website/ folder here, push it to the campbelllustblackwell.github.io site

name: push_website_to_io

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --single-branch --branch "main" "https://${{ secrets.API_TOKEN_GITHUB }}@github.com/campbellluggblackwell/campbellluggblackwell.com.git source
      - run: git clone --single-branch --branch "main" "https://${{ secrets.API_TOKEN_GITHUB }}@github.com/campbellluggblackwell/campbellluggblackwell.github.io.git destination
      - run: ls
      - run: ls source
      - run: ls destination
